#ifndef VITAMATERIALKIT_SCREEN_HH
#define VITAMATERIALKIT_SCREEN_HH

#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 544
#define SCREEN_HALF_WIDTH SCREEN_WIDTH/2
#define SCREEN_HALF_HEIGHT SCREEN_HEIGHT/2

#endif //VITAMATERIALKIT_SCREEN_HH
